# All values in no of frames
BACKGROUND_COLOR: darkgray
BREAK_TIME: 60
FRAME_RATE: 60
FIX_CROSS_TIME: 48
NO_TRAINING_TRIALS: 12
INTRA_BLOCK_TRAINIG: 32
NO_BLOCKS: 4
FIX_CROSS_COLOR: black
STIM_TYPES: [X, X X X X X, C C X C C, B B X B B, V V X V V, N Z X N Z, O G X O G, C, X X C X X, C C C C C, B B C B B, O G C G O, V V C V V, N Z C N Z, B, X X B X X, C C B C C, B B B B B, V V B V V, P D B P D, N Z B N Z, V, X X V X X, C C V C C, B B V B B, V V V V V, N Z V N Z, P D V P D]
STIM_SIZE: 50
FIX_CROSS_SIZE: 100
FEEDBACK_SIZE: 30
STIM_TIME: 240
REACTION_KEYS: [a, l]
STIM_COLOR: black

